---
title: "Shifted Peaks Data"
format: gfm
---

Load packages:

```{r}
#| message: false
library(dplyr)
library(ggplot2)
library(purrr)
```

Specify parameters: 

```{r}
z1 = 1; z1_sd = 0.05; a1 = -3; a1_sd = 1
z2 = 1.25; z2_sd = 0.05; a2 = 3; a2_sd = 1
```

Specify the times:

```{r}
times = seq(-15, 15, length.out = 150)
```

Functions: 

```{r}
# Function for simulating data
generate_data = function(id, group, t) {
  if (group == 1) {
    z = rnorm(1, z1, z1_sd)
    a = rnorm(1, a1, a1_sd)
  }
  if (group == 2) {
    z = rnorm(1, z2, z2_sd)
    a = rnorm(1, a2, a2_sd)
  }
  y = z * exp((-((t - a)^2)) / 2)

  data.frame(id, group = as.character(group), index = 1:length(t), t, y)
}

# Function for generating true means
true_mean = function(group, t) {
  if (group == 1) {
   z = z1
   a = a1
  }
  if (group == 2) {
    z = z2
    a = a2
  }
  y = z * exp((-((t - a)^2)) / 2)
  data.frame(group = as.character(group), index = 1:length(t), t, y)
}
```

Specify the sample sizes: 

```{r}
ntrain = 400
ntest = 100
n = ntrain + ntest
```

Simulate data: 

```{r}
set.seed(20211027)
shifted_peaks_data <-
  map2_df(
    .x = 1:n,
    .y = c(rep(1:2, each = n / 2)),
    .f = generate_data,
    t = times
  )
```

Randomly select ids from the simulated data for the training data: 

```{r}
train_ids = sample(unique(shifted_peaks_data$id), ntrain, F)
```

Add training/testing variable:

```{r}
shifted_peaks_data <- 
  shifted_peaks_data |>
  mutate(data = ifelse(id %in% train_ids, "Training", "Testing")) |>
  select(data, id, group, everything()) |>
  mutate(data = forcats::fct_relevel(data, "Training", "Testing")) |>
  mutate(group = factor(group))
```

Generate true functional means: 

```{r}
shifted_peaks_true_means <- 
  bind_rows(true_mean(1, times), true_mean(2, times)) |> 
  select(-index) |>
  mutate(group = factor(group, levels = c("1", "2")), t = round(t,2)) |>
  rename(mean_true = y)
```

Join data, params, and means in a list:

```{r}
shifted_peaks <- 
  list(
    data = shifted_peaks_data,
    params = list(z1 = 1, z1_sd = 0.05, a1 = -3, a1_sd = 1, z2 = 1.25, z2_sd = 0.05, a2 = 3, a2_sd = 1),
    true_means = shifted_peaks_true_means
  )
```

Plot of the data:

```{r}
#| fig-width: 16
#| fig-height: 4
ggplot(shifted_peaks$data, aes(x = t, y = y, color = group, group = id)) +
  geom_line(alpha = 0.35) +
  facet_grid(. ~ data) +
  theme_bw() +
  scale_color_manual(values = wesanderson::wes_palettes$Royal1[2:1]) +
  ylim(0, 1.4) + 
  guides(color = guide_legend(override.aes = list(alpha = 1))) +
  labs(
    color = "Group",
    title = "Simulated functions",
    x = "Time",
    y = "y"
  )
```

Plot the means: 

```{r}
#| fig-width: 8
#| fig-height: 4
shifted_peaks$true_means |>
  ggplot(aes(x = t, y = mean_true, group = group, color = group)) +
  geom_line() +
  labs(
    title = "Functional means", 
    y = "y",
    x = "t",
    color = "Group"
  ) +
  scale_color_manual(values = wesanderson::wes_palettes$Royal1[2:1]) +
  theme_bw() +
  ylim(0, 1.4)
```

Save the simulated data and true means:

```{r}
save(shifted_peaks, file = "../data/shifted_peaks.rda")
```
